[package]
name = "rw_resource_util"
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
fs-err = "2"
sysinfo = { version = "0.31", default-features = false, features = ["system"] }
thiserror-ext = { workspace = true }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
