[server]
telemetry_enabled = false
metrics_level = "Disabled"

[system]
max_concurrent_creating_streaming_jobs = 0

[meta]
meta_leader_lease_secs = 10

[meta.developer]
meta_actor_cnt_per_worker_parallelism_soft_limit = 65536
meta_actor_cnt_per_worker_parallelism_hard_limit = 65536